# Generated by Django 3.2.25 on 2026-06-20 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('religion', models.CharField(choices=[('hindu', 'Hindu'), ('christian', 'Christian'), ('muslim', 'Muslim'), ('others', 'Others')], max_length=20)),
                ('caste', models.CharField(blank=True, max_length=100)),
                ('subcaste', models.CharField(blank=True, max_length=100)),
                ('mother_tongue', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='never_married', max_length=20)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.IntegerField(blank=True, null=True)),
                ('skin_tone', models.CharField(blank=True, max_length=50)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, choices=[('school', 'School'), ('diploma', 'Diploma'), ('ug', 'Under Graduate'), ('pg', 'Post Graduate'), ('phd', 'PhD')], max_length=20)),
                ('education_detail', models.CharField(blank=True, max_length=200)),
                ('employment_type', models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('business', 'Business'), ('not_working', 'Not Working')], max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('annual_income', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('brothers', models.IntegerField(default=0)),
                ('sisters', models.IntegerField(default=0)),
                ('family_type', models.CharField(blank=True, choices=[('nuclear', 'Nuclear'), ('joint', 'Joint')], max_length=20)),
                ('family_status', models.CharField(blank=True, choices=[('middle', 'Middle Class'), ('upper_middle', 'Upper Middle Class'), ('rich', 'Rich')], max_length=20)),
                ('star', models.CharField(blank=True, max_length=50)),
                ('rasi', models.CharField(blank=True, max_length=50)),
                ('lagnam', models.CharField(blank=True, max_length=50)),
                ('chevvai_dosham', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=20)),
                ('sarpa_dosham', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='dont_know', max_length=20)),
                ('about', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, default=None, null=True, upload_to='profile_photos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('profile_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(default=18)),
                ('max_age', models.IntegerField(default=35)),
                ('min_height', models.IntegerField(default=140)),
                ('max_height', models.IntegerField(default=200)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('caste', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=50)),
                ('employment', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('dosham_ok', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
