# Generated by Django 4.2.30 on 2026-06-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hide_photo",
            field=models.BooleanField(
                default=False,
                help_text="If checked, photo is hidden from public search results",
            ),
        ),
    ]
