# Generated by Django 4.2.30 on 2026-06-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("interest_received", "Interest Received"),
                    ("interest_accepted", "Interest Accepted"),
                    ("interest_rejected", "Interest Rejected"),
                    ("profile_approved", "Profile Approved"),
                    ("profile_rejected", "Profile Rejected"),
                    ("new_match", "New Match"),
                    ("subscription", "Subscription"),
                    ("daily_matches", "Daily Match Suggestions"),
                ],
                max_length=30,
            ),
        ),
    ]
